version: "3.7"
services:

  postman:
    image: sunil016/stock_exchange_order:1.0
    ports:
      - "8000"
    networks:
      - frontend
    deploy:
      replicas: 10
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
    depends_on: 
        - db

  db:
    image: mongo:3-xenial
    volumes:
      - "/data/db:/data/db"
    networks:
      - backend
    deploy:
        placement:
            constraints:
                - "node.role==manager"

  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8080:8080"
    stop_grace_period: 1m30s
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints:
          - "node.role==manager"

networks:
  frontend:
  backend: